version: "3.3"
services:
  api:
    build: .
    container_name: sensu-api
    links:
      - redis
    command: api
    networks:
      - frontend
    ports:
      - '4567:4567'

  server:
    container_name: sensu-server
    build : .
    links:
      - redis
      - api
    command: server
    networks:
      - frontend

  client:
    container_name: sensu-client
    build: .
    links:
      - redis
    environment:
      CLIENT_NAME: test
      CLIENT_SUBSCRIPTIONS: all
      CLIENT_ADDRESS: 127.0.0.1
      HOST_DEV_DIR: /host_dev
      HOST_PROC_DIR: /host_proc
      HOST_SYS_DIR: /host_sys
    ports:
      - '3030:3030'
    command: client
    networks:
      - frontend
    volumes:
      - /dev:/host_dev:ro
      - /proc:/host_proc:ro
      - /sys:/host_sys:ro

  redis:
    container_name: sensu-redis
    image: redis:3
    networks:
      - frontend

  uchiwa:
    image: sstarcher/uchiwa
    container_name: sensu-uchiwa
    environment:
      SENSU_DC_NAME: test
      SENSU_HOSTNAME: api
    links:
      - api
    ports:
      - '80:3000'
    networks:
      - frontend

networks:
  frontend: